#!/bin/bash
set -e

BARMAN_POSTGRES_USER=${BARMAN_POSTGRES_USER:-barman}
BARMAN_POSTGRES_PASSWORD=${BARMAN_POSTGRES_PASSWORD:-password}
BARMAN_POSTGRES_STREAMING_USER=${BARMAN_POSTGRES_STREAMING_USER:-streaming_barman}
BARMAN_POSTGRES_STREAMING_PASSWORD=${BARMAN_POSTGRES_STREAMING_PASSWORD:-password}

echo "host replication ${BARMAN_POSTGRES_STREAMING_USER} all scram-sha-256" >> "${PGDATA}/pg_hba.conf"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$do\$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles WHERE rolname = '${BARMAN_POSTGRES_USER}'
   ) THEN
      CREATE USER ${BARMAN_POSTGRES_USER} WITH SUPERUSER PASSWORD '${BARMAN_POSTGRES_PASSWORD}';
   END IF;
   
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles WHERE rolname = '${BARMAN_POSTGRES_STREAMING_USER}'
   ) THEN
      CREATE USER ${BARMAN_POSTGRES_STREAMING_USER} WITH REPLICATION PASSWORD '${BARMAN_POSTGRES_STREAMING_PASSWORD}';
   END IF;
END
\$do\$;
EOSQL
